### ISSUE TITLE
部署完之后页面空白

### ISSUE THREAD

**Issue by Meeeeeet6** [jinghu-moon/ssl-monitor#1]
作者大大您好，想问一下按照教程部署完成并绑定自定义域名之后，打开页面显示空白如何处理？
![image](https://user-images.githubusercontent.com/74605260/208913074-2bc29389-08ec-4aa2-84ae-0a45fabadb16.png)

**Comment by jinghu-moon** [comment]
你这个是本地预览吧？建议使用 vercel 部署使用。注意 vercel 的子域名在大陆范围无法使用，需要绑定自己的域名。

**Comment by Meeeeeet6** [comment]
> 
不是，是根据您Readme里面的Github Page方法部署的，产生了一个新的gh-page分支之后，我用Github Pages连接到该分支并绑定自定义域名，打开就是这个样子，什么信息都没有。顺便向请教一下您，Vercel如何部署使用？

**Comment by jinghu-moon** [comment]
1、访问 [vercel](https://vercel.com/)，用 GitHub 账户登录。

2、跳转 [Dashboard – Vercel](https://vercel.com/dashboard) ， 点击 右上角 `Add New...` → `Project`。

3、点击 `Import`导入 GitHub 项目 Later-Debug/ssl-monitor。

4、直接 `Deploy` ，开始部署。

5、转到项目 `Settings` → `Git` ，`Production Branch` 改为 `gh-pages` 。

6、本地推送代码到 GitHub，vercel 会自动部署。

这样应该可以了。

**Comment by Meeeeeet6** [comment]
> 

已按照教程尝试部署，但仍然显示空白页面。域名是：https://ssl-monitor.vercel.app/
问题仍然存在，向大神请教如何处理！
情况如下图所示：

![image](https://user-images.githubusercontent.com/74605260/208923213-25b0c4cf-8bf1-48ea-9af3-3cdec1c9d471.png)
![image](https://user-images.githubusercontent.com/74605260/208923240-a1d47ffc-b002-4378-a52f-585ebed9772a.png)
![image](https://user-images.githubusercontent.com/74605260/208923425-4e621b65-1734-416b-b8d9-3530fa6c848b.png)

**Comment by jinghu-moon** [comment]
你是不是仓库没有绑定 `TOKEN`？刚才我测试了下。第五步后面绑定 `TOKEN` ，就可以了

**Comment by jinghu-moon** [comment]
https://test-mnui8alcn-jinghu-moon.vercel.app/ 测试的域名

**Comment by Meeeeeet6** [comment]
绑定了。甚至现在再重新绑定，重新部署之后仍然不行。
![image](https://user-images.githubusercontent.com/74605260/208937702-20cf9342-fd37-4809-8d92-0f89b4af601c.png)

![image](https://user-images.githubusercontent.com/74605260/208937712-17c8caab-88c3-4347-8ce3-b44d7a4c5947.png)

**Comment by jinghu-moon** [comment]
vercel 重新部署下，再清除下网页缓存试试。我都可以呀。

**Comment by Meeeeeet6** [comment]
非常玄学，已经尝试了。仍然是空白状态。
地址：https://testteattestsslmonitor.vercel.app/
![image](https://user-images.githubusercontent.com/74605260/208942207-af2a5985-7ccf-4d11-86fe-c03b4d962d3c.png)
![image](https://user-images.githubusercontent.com/74605260/208942246-e57e57e6-d132-4ba4-aae9-99905f7d1f9e.png)
![image](https://user-images.githubusercontent.com/74605260/208942292-885da2f3-8a7b-4062-a3eb-724ca0ae3f0a.png)
![1671636768581](https://user-images.githubusercontent.com/74605260/208942609-c5f64ee7-aa30-4709-b097-957f9135c1b0.png)
![image](https://user-images.githubusercontent.com/74605260/208942701-6a353c90-419f-41ad-825f-927dc7c6937b.png)
如图所示，非常玄学，反正就是加载不出来。

**Comment by Meeeeeet6** [comment]
发现一个玄学操作，在Vercel部署完成之后
进入gh-pages分支，修改index.html文件
![image](https://user-images.githubusercontent.com/74605260/208945710-83cfe977-e104-44e6-a674-ea0ef84e6bc2.png)
将这里的./改为https开头的域名，即可正常显示。虽然不知道为什么好神奇
![image](https://user-images.githubusercontent.com/74605260/208945911-e201ee1a-0bb2-4c0d-be89-c573d3c6bc00.png)

**Comment by jinghu-moon** [comment]
好吧，后面有时间，我在重写下代码。最近在写 Typora 主题。没时间。

**Comment by Meeeeeet6** [comment]
多次尝试后，重新部署到了Cloudflare Pages成功显示，至于前面为什么不显示原因我也不得而知，但可以用来。麻烦您了，谢谢
